In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from __future__ import division
from datetime import datetime
from time import time
a = time()
import threading

In [2]:
%%time
df_et = pd.read_csv('C:/Users/Shruthi/Downloads/lab11_data/events_train.tsv', sep="\t")
df_pt = pd.read_csv('C:/Users/Shruthi/Downloads/lab11_data/prediction_trials.tsv', sep="\t")
df_pt_final = pd.read_csv('C:/Users/Shruthi/Downloads/lab11_data/prediction_trials.tsv', sep="\t")

Wall time: 9.22 s

In [3]:
#Accidents and Incidents (A).
#2. Roadwork (R).
#3. Precipitation (P).
#4. Device Status (D).
#5. Obstruction (O).
#6. Traffic Conditions (T).
et = ['A', 'R', 'P', 'D', 'O', 'T']
et_str = ['accidentsAndIncidents', 'roadwork', 'precipitation','deviceStatus','obstruction','trafficConditions']
#et_d = {'A': 'accidentsAndIncidents', 'R': 'roadwork', 'P': 'precipitation', 'D': 'deviceStatus', 'O': 'obstruction', \
#        'T': 'trafficConditions'}
et_d = {'accidentsAndIncidents': 'A', 'roadwork': 'R', 'precipitation': 'P', 'deviceStatus': 'D', 'obstruction': 'O', \
        'trafficConditions': 'T'}

comb_str = []
#for i in range(2003, 2004):
for i in range(2003, 2017):
    for j in et:
        comb_str.append('%d%s'%(i,j))
#comb_str, et_d

In [4]:
year=range(2003, 2014)

In [5]:
year

range(2003, 2014)

In [6]:
for i in comb_str:
    #df_pt[i] = 0
    df_pt_final[i] = 0
hdrs = df_pt.columns.values.tolist()

In [7]:
maxlat = max(df_pt['nw_lat'])
minlat = min(df_pt['se_lat'])
maxlon = max(df_pt['se_lon'])
minlon = min(df_pt['nw_lon'])
maxlat, minlat

(39.328541143708641, 38.727325193834155)

In [ ]:
maxlat, maxlon

In [8]:
len(df_et)

844049

In [9]:
df_et = df_et[df_et['latitude'] <= maxlat]
df_et = df_et[df_et['latitude'] >= minlat]
df_et = df_et[df_et['longitude'] <= maxlon]
df_et = df_et[df_et['latitude'] >= minlon]
len(df_et)
#df_pt_nw_lat['nw_lat'] >= tmp_lat

721670

In [9]:
num = len(df_et)

begn = 0
#num = 10000

t1 = time()
for i in range(begn+ int(num/5)):
    try:
        event_type = et_d[df_et['event_type'][i]]
    except KeyError:
        continue
        
    yr = df_et['closed_tstamp'][i][:4]
    tmp_str_comb = '%s%s' %(yr, event_type)
    
    tmp_lat = df_et['latitude'][i]
    tmp_lon = df_et['longitude'][i]
    
    df_pt_final.loc[((df_pt_final['nw_lat'] >= tmp_lat) &  (df_pt_final['se_lat'] <= tmp_lat) &  
                     (df_pt_final['nw_lon'] <= tmp_lon) &  (df_pt_final['se_lon'] >= tmp_lon)), tmp_str_comb] += 1
t2 = time()
print ('20% complete in ', t2-t1)

for i in range(begn+ int(num/5), begn+ int(2*num/5)):
    try:
        event_type = et_d[df_et['event_type'][i]]
    except KeyError:
        continue
        
    yr = df_et['closed_tstamp'][i][:4]
    tmp_str_comb = '%s%s' %(yr, event_type)
    
    tmp_lat = df_et['latitude'][i]
    tmp_lon = df_et['longitude'][i]
    
    df_pt_final.loc[((df_pt_final['nw_lat'] >= tmp_lat) &  (df_pt_final['se_lat'] <= tmp_lat) &  
                     (df_pt_final['nw_lon'] <= tmp_lon) &  (df_pt_final['se_lon'] >= tmp_lon)), tmp_str_comb] += 1
t2 = time()
print ('40% complete in ', t2-t1)

for i in range(begn+ int(2*num/5), begn+ int(3*num/5)):
    try:
        event_type = et_d[df_et['event_type'][i]]
    except KeyError:
        continue
        
    yr = df_et['closed_tstamp'][i][:4]
    tmp_str_comb = '%s%s' %(yr, event_type)
    
    tmp_lat = df_et['latitude'][i]
    tmp_lon = df_et['longitude'][i]
    
    df_pt_final.loc[((df_pt_final['nw_lat'] >= tmp_lat) &  (df_pt_final['se_lat'] <= tmp_lat) &  
                     (df_pt_final['nw_lon'] <= tmp_lon) &  (df_pt_final['se_lon'] >= tmp_lon)), tmp_str_comb] += 1
t2 = time()
print ('60% complete in ', t2-t1)

for i in range(begn+ int(3*num/5), begn+ int(4*num/5)):
    try:
        event_type = et_d[df_et['event_type'][i]]
    except KeyError:
        continue
        
    yr = df_et['closed_tstamp'][i][:4]
    tmp_str_comb = '%s%s' %(yr, event_type)
    
    tmp_lat = df_et['latitude'][i]
    tmp_lon = df_et['longitude'][i]
    
    df_pt_final.loc[((df_pt_final['nw_lat'] >= tmp_lat) &  (df_pt_final['se_lat'] <= tmp_lat) &  
                     (df_pt_final['nw_lon'] <= tmp_lon) &  (df_pt_final['se_lon'] >= tmp_lon)), tmp_str_comb] += 1
t2 = time()
print ('80% complete in ', t2-t1)

for i in range(begn+ int(4*num/5), begn+ int(num)):
    try:
        event_type = et_d[df_et['event_type'][i]]
    except KeyError:
        continue
        
    yr = df_et['closed_tstamp'][i][:4]
    tmp_str_comb = '%s%s' %(yr, event_type)
    
    tmp_lat = df_et['latitude'][i]
    tmp_lon = df_et['longitude'][i]
    
    df_pt_final.loc[((df_pt_final['nw_lat'] >= tmp_lat) &  (df_pt_final['se_lat'] <= tmp_lat) &  
                     (df_pt_final['nw_lon'] <= tmp_lon) &  (df_pt_final['se_lon'] >= tmp_lon)), tmp_str_comb] += 1
t2 = time()
print ('100% complete in ', t2-t1)

20% complete in  1278.5662457942963
40% complete in  2523.902812242508
60% complete in  3886.8150005340576
80% complete in  5348.641509771347
100% complete in  6751.941169261932

In [10]:
fname= 'df%dfinal.txt'%(begn+num)

df_pt_final.to_csv(fname,sep='\t', index=False, header=True)

In [3]:
df_pt_final=pd.read_csv('C:/Users/Shruthi/Downloads/df721670final.txt', sep="\t")

In [196]:
df_pt_final.ix[0]

trial_id                      p_00000001
nw_lat                            39.183
nw_lon                          -76.7987
se_lat                           39.1702
se_lon                          -76.7781
start          2015-02-01T00:00:00-05:00
end            2015-03-01T00:00:00-05:00
2003A                                  1
2003R                                  0
2003P                                  0
2003D                                  0
2003O                                  0
2003T                                  0
2004A                                 18
2004R                                  0
2004P                                  0
2004D                                  0
2004O                                  0
2004T                                  0
2005A                                 22
2005R                                  0
2005P                                  0
2005D                                  0
2005O                                  1
2005T                                  0
2006A                                 31
2006R                                  0
2006P                                  0
2006D                                  0
2006O                                  0
                         ...
2012D                                  5
2012O                                 17
2012T                                  0
2013A                                467
2013R                                 27
2013P                                  0
2013D                                  7
2013O                                 23
2013T                                  0
2014A                                104
2014R                                  9
2014P                                  0
2014D                                  7
2014O                                  2
2014T                                  0
2015A                                  0
2015R                                  0
2015P                                  0
2015D                                  0
2015O                                  0
2015T                                  0
2016A                                  0
2016R                                  0
2016P                                  0
2016D                                  0
2016O                                  0
2016T                                  0
year                                2015
linear_E                               0
linear_pred                            0
Name: 0, dtype: object

In [240]:
import re

def extract_year_from_tstamp(x):
    if isinstance(x, (str)):
        year = x.split('-')[0]
        if re.search(r'[0-9]{4}', year, 0):
            return year

df_pt_final['year'] = df_pt_final['end'].apply(lambda x:extract_year_from_tstamp(x))

In [7]:
df_pt_final['linear_E']=0
df_pt_final['linear_pred']=0

In [247]:
df_pt_final[df_pt_final['year']=='2015']

,trial_id,nw_lat,nw_lon,se_lat,se_lon,start,end,2003A,2003R,2003P,...,2015T,2016A,2016R,2016P,2016D,2016O,2016T,year,linear_E,linear_pred
0,p_00000001,39.182985,-76.798663,39.170238,-76.778150,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
2,p_00000003,38.946840,-76.783484,38.931581,-76.761971,2015-03-01T00:00:00-05:00,2015-04-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
3,p_00000004,38.996686,-77.159555,38.982995,-77.140682,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,4,1,0,...,0,0,0,0,0,0,0,2015,0,0
5,p_00000006,38.784610,-77.240293,38.778743,-77.229930,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
6,p_00000007,38.870283,-77.010676,38.860996,-76.987956,2015-10-19T00:00:00-05:00,2015-11-07T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
7,p_00000008,38.876769,-77.297809,38.860953,-77.284259,2015-08-15T00:00:00-05:00,2015-09-11T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
8,p_00000009,39.232291,-76.670215,39.216349,-76.647555,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,7,0,0,...,0,0,0,0,0,0,0,2015,0,0
10,p_00000011,38.892547,-77.222727,38.876989,-77.202233,2015-10-22T00:00:00-05:00,2015-11-03T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
11,p_00000012,39.292767,-76.560125,39.282763,-76.538952,2015-06-08T00:00:00-05:00,2015-06-29T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
12,p_00000013,38.964793,-77.104645,38.951858,-77.089515,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
13,p_00000014,38.888757,-77.117359,38.873618,-77.109529,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
14,p_00000015,39.059560,-76.853824,39.053927,-76.832445,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
15,p_00000016,39.217099,-76.656704,39.201526,-76.641332,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
16,p_00000017,38.995192,-76.995103,38.982501,-76.973085,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
18,p_00000019,39.131578,-77.075792,39.117087,-77.066004,2015-01-12T00:00:00-05:00,2015-02-11T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
19,p_00000020,39.088912,-77.174252,39.074104,-77.158851,2015-07-21T00:00:00-05:00,2015-08-06T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
20,p_00000021,38.860380,-77.082445,38.844184,-77.060488,2015-07-06T00:00:00-05:00,2015-07-15T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
21,p_00000022,39.257882,-76.732488,39.244203,-76.713033,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
22,p_00000023,38.873831,-76.857039,38.857741,-76.839339,2015-03-01T00:00:00-05:00,2015-04-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
23,p_00000024,38.887978,-76.975761,38.871660,-76.966322,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
24,p_00000025,39.199682,-76.774338,39.189953,-76.756826,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,2,0,0,...,0,0,0,0,0,0,0,2015,0,0
25,p_00000026,38.802353,-77.104809,38.790391,-77.085065,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
26,p_00000027,38.823285,-77.172163,38.806981,-77.152418,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
27,p_00000028,38.892624,-77.291161,38.876013,-77.271339,2015-09-04T00:00:00-05:00,2015-09-04T19:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
28,p_00000029,38.883791,-77.246097,38.872352,-77.236816,2015-01-17T00:00:00-05:00,2015-02-16T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
29,p_00000030,38.960218,-76.881502,38.952286,-76.862340,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,5,0,0,...,0,0,0,0,0,0,0,2015,0,0
30,p_00000031,39.270525,-76.719870,39.256917,-76.700512,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,2,0,0,...,0,0,0,0,0,0,0,2015,0,0
31,p_00000032,39.021945,-76.960958,39.012268,-76.940340,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
32,p_00000033,39.017612,-77.153670,39.008267,-77.130408,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,4,0,0,...,0,0,0,0,0,0,0,2015,0,0
33,p_00000034,39.266064,-76.576726,39.253460,-76.558051,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328384,p_00328385,39.026999,-77.155160,39.019046,-77.137081,2015-03-01T00:00:00-05:00,2015-04-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328385,p_00328386,38.852229,-77.097808,38.835915,-77.075438,2015-03-01T00:00:00-05:00,2015-04-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328386,p_00328387,38.990080,-77.095999,38.980635,-77.079425,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328387,p_00328388,38.876385,-77.345144,38.861185,-77.323065,2015-09-24T00:00:00-05:00,2015-10-14T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328388,p_00328389,38.874573,-77.327391,38.863117,-77.306463,2015-03-26T00:00:00-05:00,2015-03-28T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328389,p_00328390,38.812629,-76.777500,38.794793,-76.757287,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328390,p_00328391,39.079185,-77.171161,39.070536,-77.160899,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328391,p_00328392,38.853868,-76.964825,38.841571,-76.943692,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328392,p_00328393,39.182831,-76.805404,39.167777,-76.784404,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328393,p_00328394,38.811197,-77.136039,38.798602,-77.112926,2015-03-01T00:00:00-05:00,2015-04-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328394,p_00328395,39.175280,-76.646998,39.159625,-76.630926,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,3,0,0,...,0,0,0,0,0,0,0,2015,0,0
328395,p_00328396,38.971788,-77.184231,38.956705,-77.178290,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328396,p_00328397,39.269224,-76.704148,39.259997,-76.686448,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328397,p_00328398,38.884049,-77.246478,38.870641,-77.226948,2015-09-25T00:00:00-05:00,2015-10-20T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328398,p_00328399,38.806377,-77.079652,38.794130,-77.068651,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328400,p_00328401,38.912341,-77.005811,38.898915,-76.996123,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328401,p_00328402,38.910923,-77.031670,38.900256,-77.012206,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328403,p_00328404,39.021706,-76.698111,39.005158,-76.689599,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328404,p_00328405,38.861803,-76.963203,38.844162,-76.950368,2015-03-06T00:00:00-05:00,2015-03-30T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328405,p_00328406,38.931844,-77.044822,38.917047,-77.027380,2015-09-19T00:00:00-05:00,2015-10-16T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328406,p_00328407,38.782857,-77.183123,38.774581,-77.176813,2015-03-30T00:00:00-05:00,2015-04-18T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328407,p_00328408,38.797080,-77.056347,38.779740,-77.038726,2015-03-01T00:00:00-05:00,2015-04-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328408,p_00328409,38.910227,-77.021304,38.897485,-77.009943,2015-12-14T00:00:00-05:00,2015-12-25T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328409,p_00328410,38.772582,-76.892597,38.760860,-76.884855,2015-03-01T00:00:00-05:00,2015-04-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328410,p_00328411,38.861894,-77.221048,38.856226,-77.203752,2015-01-01T00:00:00-05:00,2015-02-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328411,p_00328412,38.982737,-77.184954,38.965571,-77.176144,2015-12-09T00:00:00-05:00,2015-12-22T00:00:00-05:00,2,0,0,...,0,0,0,0,0,0,0,2015,0,0
328412,p_00328413,39.166521,-76.702234,39.158383,-76.691183,2015-02-01T00:00:00-05:00,2015-03-01T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0
328413,p_00328414,39.200268,-76.789002,39.185724,-76.766378,2015-02-11T00:00:00-05:00,2015-03-12T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328414,p_00328415,38.968202,-76.958635,38.953418,-76.936959,2015-04-01T00:00:00-05:00,2015-05-01T00:00:00-05:00,1,0,0,...,0,0,0,0,0,0,0,2015,0,0
328415,p_00328416,39.074792,-76.909927,39.060618,-76.902272,2015-04-04T00:00:00-05:00,2015-04-28T00:00:00-05:00,0,0,0,...,0,0,0,0,0,0,0,2015,0,0

In [248]:
df_pt_final['year']=np.where(df_pt_final['year']=='2015' ,12 ,13)

In [25]:
train_X=np.array([0,1,2,3,4,5,6,7,8,9,10])
train_Y= df_pt_final[['2003R','2004R','2005R', '2006R','2007R','2008R','2009R','2010R','2011R','2012R','2013R']]
validation_Y=np.array(df_pt_final[['2014R']])
#regr = linear_model.LinearRegression()
clf=linear_model.LinearRegression().fit(train_X.reshape(11,1),train_Y.transpose())
clf.predict(validation_X)
df_pt_final['linear_E'].ix[i]=(pred - validation_Y) ** 2

NameError: name 'validation_X' is not defined

In [27]:
train_Y.transpose()

,0,1,2,3,4,5,6,7,8,9,...,328406,328407,328408,328409,328410,328411,328412,328413,328414,328415
2003R,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2004R,0,0,0,0,0,0,0,0,1,1,...,0,1,0,0,0,0,0,0,0,0
2005R,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
2006R,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2007R,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,3,0
2008R,9,0,1,1,0,0,0,0,9,0,...,0,0,0,0,0,6,0,5,0,0
2009R,3,0,4,33,0,0,0,8,79,1,...,91,191,0,0,5,140,0,3,4,0
2010R,8,1,32,25,26,0,0,17,59,0,...,159,66,0,0,4,170,0,3,2,0
2011R,9,7,1,8,120,1,0,31,125,6,...,107,73,1,7,5,128,1,11,58,4
2012R,30,2,8,37,112,26,1,24,208,6,...,188,104,8,8,5,179,3,49,95,21
2013R,27,4,2,23,145,19,0,43,193,5,...,230,57,1,9,12,169,13,34,114,78

In [202]:
import numpy.polynomial.polynomial as poly

train_X=np.array([0,1,2,3,4,5,6,7,8,9,10])
train_Y= df_pt_final[['2003R','2004R','2005R', '2006R','2007R','2008R','2009R','2010R','2011R','2012R','2013R']]
validation_X=np.array([11])
validation_Y=np.array(df_pt_final[['2014A']])
coefs = poly.polyfit(train_X.reshape(1,11), train_Y, 2)
pred = poly.polyval(validation_X, coefs)
E=(pred - validation_Y) ** 2

TypeError: expected 1D vector for x

In [198]:
df_pt_final[['2003A','2004A','2005A', '2006A','2007A','2008A','2009A','2010A','2011A','2012A','2013A','2014A']]

,2003A,2004A,2005A,2006A,2007A,2008A,2009A,2010A,2011A,2012A,2013A,2014A
0,1,18,22,31,47,40,114,161,278,513,467,104
1,0,2,3,2,2,0,13,10,9,11,10,6
2,1,4,5,1,3,40,83,145,149,119,102,60
3,4,28,24,17,54,63,234,220,220,195,237,174
4,2,5,6,6,16,28,16,131,545,426,496,192
5,0,0,0,0,0,0,0,0,1,26,25,4
6,0,0,0,0,0,2,7,6,10,1063,204,51
7,0,0,0,0,0,6,101,155,260,456,336,198
8,7,13,94,80,110,186,442,577,727,790,895,397
9,2,4,9,3,7,4,7,17,20,21,13,18
10,0,0,0,0,0,56,1248,1524,1525,1218,987,458
11,0,1,3,0,4,3,6,32,151,127,120,47
12,0,0,0,0,1,0,0,2,2,3,6,1
13,0,0,0,0,0,2,11,15,7,40,30,20
14,0,4,9,3,6,56,140,176,144,350,225,100
15,1,3,20,17,30,35,71,95,138,149,184,80
16,1,3,8,1,6,11,30,39,20,19,24,10
17,0,0,0,1,2,0,1,8,3,8,16,4
18,0,0,1,0,2,2,5,3,168,344,271,100
19,0,9,12,9,28,47,168,192,210,223,187,77
20,0,1,0,0,0,30,599,802,749,1022,824,335
21,0,0,2,1,1,1,8,18,5,13,3,2
22,1,9,8,9,26,62,107,118,139,139,220,152
23,0,0,0,0,0,4,2,1,7,513,107,24
24,2,12,36,48,70,69,203,319,482,880,764,193
25,0,0,0,0,1,8,181,275,226,91,97,70
26,0,0,0,0,0,20,318,359,325,221,109,48
27,0,0,0,0,0,14,579,734,716,857,686,285
28,0,0,1,0,0,7,282,389,485,609,508,275
29,5,23,45,25,31,66,208,226,180,204,257,164
...,...,...,...,...,...,...,...,...,...,...,...,...
328386,1,1,2,0,2,0,7,8,2,5,10,6
328387,0,0,0,0,0,9,102,121,190,391,317,121
328388,0,0,0,0,0,23,734,716,853,796,785,333
328389,0,0,1,1,0,2,3,6,11,4,6,5
328390,1,6,6,3,20,36,131,114,161,152,94,60
328391,0,1,2,1,4,7,17,14,13,23,7,14
328392,1,15,22,25,47,40,120,166,282,513,465,101
328393,0,1,0,0,0,5,361,429,396,663,645,289
328394,3,7,26,20,30,28,92,123,155,181,154,75
328395,1,17,25,13,24,27,485,409,379,432,312,184
328396,0,2,12,8,12,4,8,18,3,3,8,1
328397,0,0,1,0,0,23,836,1042,1119,1132,1021,499
328398,0,0,0,0,0,8,325,406,511,596,553,228
328399,0,4,4,4,4,7,250,329,288,500,473,186
328400,0,0,0,0,0,0,4,1,12,379,87,33
328401,0,0,3,0,0,4,3,2,24,1043,297,82
328402,0,1,0,0,0,27,584,783,739,985,798,323
328403,0,0,1,0,8,4,7,25,9,16,9,8
328404,0,1,2,1,4,5,15,7,9,35,9,13
328405,0,0,1,0,0,2,2,1,5,319,52,12
328406,0,0,0,0,0,13,458,557,411,500,605,342
328407,1,17,46,15,9,11,56,90,144,372,434,214
328408,0,0,4,0,0,3,1,4,20,810,217,60
328409,0,0,0,0,1,3,12,20,10,16,14,21
328410,0,0,0,0,0,16,376,458,313,214,111,50
328411,2,29,29,16,34,39,522,568,542,555,393,249
328412,0,0,1,0,3,4,12,16,10,13,18,4
328413,1,2,7,11,21,47,180,294,485,876,767,194
328414,1,1,4,0,12,7,29,50,32,25,18,13
328415,0,0,1,0,1,0,0,0,20,224,295,155

In [203]:
%matplotlib inline
x = np.arange(0,11)
y=train_Y
ax.plot(x,y,color='red',linewidth=3)
fig, ax = plt.subplots(figsize=(16, 8))
import numpy.polynomial.polynomial as poly

coefs = poly.polyfit(x, y, 5)
ffit = poly.polyval(x, coefs)
plt.plot(x, ffit)

abline_values = [regr.coef_ * i + regr.intercept_ for i in x]
ax.plot(x, abline_values, 'b')
ax.scatter(x,y)

ValueError: x and y must have same first dimension

In [38]:
len(train.ix[0].values)

13

In [78]:
train_Y.shape

(11,)

In [81]:
train_X.shape

(11,)

In [88]:
validation_X

In [137]:
fit

array([  8.04778555, -31.34149184,  28.85314685])

In [190]:
df_pt_final['E'].ix[0]

0

In [41]:
n = 10       # size of my x,y,z dimensions
degree = 1   # degree of my polyfit
time_len = 11
A = np.random.rand(n*time_len).reshape(n,time_len)

# An x vector to regress through evenly spaced samples
X = np.arange( time_len )

In [43]:
A2 = A.reshape(time_len, -1)
regr = np.polyfit(X, A2, degree)

In [38]:
A = np.random.rand(n*n*n*time_len).reshape(n,n,n,time_len)

array([[ 0.52050527,  0.37177665,  0.96886472,  0.7186105 ,  0.87481345],
       [ 0.37043022,  0.7105908 ,  0.37214436,  0.49612871,  0.21840012],
       [ 0.17577655,  0.93125187,  0.3855266 ,  0.43020611,  0.23372315],
       [ 0.6377787 ,  0.16668443,  0.84793873,  0.61222162,  0.43100887],
       [ 0.42636681,  0.49125867,  0.44723976,  0.21241112,  0.70015334],
       [ 0.87973735,  0.06113365,  0.15737895,  0.15029813,  0.45006831],
       [ 0.7209886 ,  0.94590479,  0.02543849,  0.15970205,  0.61237044],
       [ 0.07007461,  0.02530724,  0.85549629,  0.67804312,  0.93579257],
       [ 0.62152618,  0.24327409,  0.86756083,  0.65621672,  0.8041958 ],
       [ 0.03488918,  0.8874612 ,  0.00503944,  0.56474339,  0.94236371]])

In [212]:
time_len=11
degree=2
train_X=np.arange( time_len )
train_Y= np.array(df_pt_final[['2003R','2004R','2005R', '2006R','2007R','2008R','2009R','2010R','2011R','2012R','2013R']])
validation_Y=np.array(df_pt_final[['2014R']])
validation_X=np.array([11])
#regr = linear_model.LinearRegression()
train_Y=train_Y.reshape(time_len, -1)
coefs=np.polyfit(train_X, train_Y, 1)
#poly=np.poly1d(coefs.transpose())
pred = np.polyval(coefs,validation_X)

E=(pred.transpose() - validation_Y) ** 2

MemoryError:

In [229]:
a.transpose()-validation_Y

array([[-104.        ],
       [  -5.27272727],
       [ -58.34545455],
       ...,
       [-124.10909091],
       [ 133.21818182],
       [ -58.61818182]])

In [256]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import math
time_len=11
degree=2
test_X=df_pt_final['year']
train_X=np.arange( time_len )
validation_X=np.array([11])
degrees = [1, 2, 3,4]
from sklearn import cross_validation
for i in range(len(degrees)):
    sum=0
    for k in et :
        cols=[]
        colY=[]
        colY.append('%d%s'%(2014,k))
        for j in range(2003, 2014):
            cols.append('%d%s'%(j,k))
        colPredict='Predict'+k
        train_Y= np.array(df_pt_final[cols])
        train_Y = train_Y.reshape(time_len, -1)
        validation_Y=np.array(df_pt_final[colY])
        coefs=np.polyfit(train_X, train_Y, degrees[i])
        #poly=np.poly1d(coefs.transpose())
        predict = np.polyval(coefs,validation_X)
        
        E=(predict.reshape(1,len(predict)).transpose()-validation_Y) ** 2
        sum=sum+np.sum(E)
        df_pt_final[colPredict]=np.polyval(coefs,test_X)
    print("Degree :",degrees[i] ,"Avg Error", math.sqrt(sum/(len(E)*6)))

Degree : 1 Avg Error 90.50762709991687
Degree : 2 Avg Error 113.96738658563719
Degree : 3 Avg Error 156.77445919699267
Degree : 4 Avg Error 237.40471567694084

In [261]:
df_pt_final['2014A']

0         104
1           6
2          60
3         174
4         192
5           4
6          51
7         198
8         397
9          18
10        458
11         47
12          1
13         20
14        100
15         80
16         10
17          4
18        100
19         77
20        335
21          2
22        152
23         24
24        193
25         70
26         48
27        285
28        275
29        164
         ...
328386      6
328387    121
328388    333
328389      5
328390     60
328391     14
328392    101
328393    289
328394     75
328395    184
328396      1
328397    499
328398    228
328399    186
328400     33
328401     82
328402    323
328403      8
328404     13
328405     12
328406    342
328407    214
328408     60
328409     21
328410     50
328411    249
328412      4
328413    194
328414     13
328415    155
Name: 2014A, dtype: int64

In [264]:
import math
time_len=11
degree=2
sum=0
train_X=np.arange( 1,14 )
validation_X=np.array([15])
for i in et :
    cols=[]
    colY=[]
    colY.append('%d%s'%(2014,i))
    for j in range(2003, 2014):
        cols.append('%d%s'%(j,i))
        
    train_Y= np.array(df_pt_final[cols])
    train_Y = train_Y.reshape(time_len, -1)
    validation_Y=np.array(df_pt_final[colY])
    clf=linear_model.LinearRegression().fit(train_X.reshape(11,-1),train_Y)
    p=clf.predict(validation_X)    
    E=(p.transpose() - validation_Y) ** 2
    sum=sum+np.sum(E)
math.sqrt(sum/(len(E)*6))

ValueError: total size of new array must be unchanged

In [250]:
predictCol

'predictT'

In [270]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import math
time_len=11
degree=2

train_X=np.arange( 1,12 )
validation_X=np.array([12])
degrees = [1, 2, 3,4]
from sklearn import cross_validation
for i in range(len(degrees)):
    sum=0
    for k in et:
        cols=[]
        colY=[]
        colY.append('%d%s'%(2014,k))
        for j in range(2003, 2014):
            cols.append('%d%s'%(j,k))

        train_Y= np.array(df_pt_final[cols])
        train_Y = train_Y.reshape(time_len, -1)
        validation_Y=np.array(df_pt_final[colY])
        polynomial_features = PolynomialFeatures(degree=degrees[i],
                                                 include_bias=False)
        linear_regression = LinearRegression()
        pipeline = Pipeline([("polynomial_features", polynomial_features),
                             ("linear_regression", linear_regression)])
        pipeline.fit(train_X.reshape(11,-1), train_Y)
        
        predict=pipeline.predict(validation_X)
        E=(predict.transpose()-validation_Y) ** 2
        sum=sum+np.sum(E)
        
    print("Degree :",degrees[i] ,"Avg Error", math.sqrt(sum/(len(E)*6)))

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 1 Avg Error 90.50762709991687

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 2 Avg Error 113.9673865856371

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 3 Avg Error 156.77445919699423

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 4 Avg Error 237.4047156770025

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [192]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
degrees = [1, 2, 3,4]
from sklearn import cross_validation
for i in range(len(degrees)):
    sum=0
    for k in et :
        cols=[]
        colY=[]
        colY.append('%d%s'%(2014,k))
        for j in range(2003, 2014):
            cols.append('%d%s'%(j,k))

        train_Y= np.array(df_pt_final[cols])
        train_Y = train_Y.reshape(time_len, -1)
        validation_Y=np.array(df_pt_final[colY])
        model = make_pipeline(PolynomialFeatures(degrees[i]), Ridge())
        model.fit(train_X.reshape(11,-1), train_Y)
        y_plot = model.predict(validation_X)
        E=(y_plot.transpose()-validation_Y) ** 2
        sum=sum+np.sum(E)
        
    print("Degree :",degrees[i] ,"Avg Error", math.sqrt(sum/(len(E)*6)))

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 1 Avg Error 90.30815170384507

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 2 Avg Error 111.12892252112051

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 3 Avg Error 144.78179221626561

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

Degree : 4 Avg Error 207.55161749084803

C:\Users\Shruthi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

In [184]:
predict.transpose()

array([[   0.67272727],
       [  18.29090909],
       [  27.23636364],
       ...,
       [ 174.70909091],
       [ 323.47272727],
       [ 325.98181818]])

In [97]:
import math
math.sqrt(np.sum(E)/len(E))

60.309563971985924

In [127]:
cols

['2003T',
 '2004T',
 '2005T',
 '2006T',
 '2007T',
 '2008T',
 '2009T',
 '2010T',
 '2011T',
 '2012T',
 '2013T']

In [126]:
np.array(df_pt_final[cols])

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [129]:
clf

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [143]:
train_Y= np.array(df_pt_final[['2003R','2004R','2005R', '2006R','2007R','2008R','2009R','2010R','2011R','2012R','2013R']])

In [144]:
train_Y

array([[  0,   0,   0, ...,   9,  30,  27],
       [  0,   0,   0, ...,   7,   2,   4],
       [  0,   0,   0, ...,   1,   8,   2],
       ...,
       [  0,   0,   0, ...,  11,  49,  34],
       [  0,   0,   0, ...,  58,  95, 114],
       [  0,   0,   0, ...,   4,  21,  78]], dtype=int64)

In [158]:
 train_Y = train_Y.reshape(time_len, -1)

In [159]:
train_Y.shape

(11, 328416)

In [160]:
train_Y.reshape(time_len, -1)

array([[  1,  18,  22, ...,   6,  69, 109],
       [  0,   1,   0, ..., 472, 431, 393],
       [  2,   7,  13, ...,  27,  22,  37],
       ...,
       [  0,   0,   3, ..., 613, 865, 828],
       [  0,   1,   3, ...,   5,   3,   8],
       [  1,  37,  65, ...,  20, 224, 295]], dtype=int64)

In [161]:
train_Y.shape

(11, 328416)

In [272]:
for i in range(len(degrees)):
    sum=0
    for k in event :
        cols=[]
        colY=[]
        colY.append('%d%s'%(2014,k))
        for j in range(2003, 2014):
            cols.append('%d%s'%(j,k))
        colPredict='Predict'+k
        train_Y= np.array(df_predict[cols])
        train_Y = train_Y.transpose()
        validation_Y=np.array(df_predict[colY])
        coefs=np.polyfit(train_X, train_Y, degrees[i])
        predict = np.polyval(coefs,validation_X)
        E=(predict.reshape(1,len(predict)).transpose()-validation_Y) ** 2
        sum=sum+np.sum(E)
    print("Degree :",degrees[i] ,"Avg Error", math.sqrt(sum/(len(E)*6)))

NameError: name 'event' is not defined

In [ ]:
df_predict.loc[((df_predict['se_lat'] <= latitude) &  (df_predict['nw_lat'] >= latitude) &
                (df_predict['se_lon'] >= longitude) & (df_predict['nw_lon'] <= longitude) & )
               ,year_event]